<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllWithTag():array
    {
        return $this->createQueryBuilder('p')
            ->join('p.tags', 't')
            ->addSelect('t')
            ->getQuery()
            ->getResult();
    }

    public function findAllByTagName(string $name):array
    {
        return $this->createQueryBuilder('p')
            ->join('p.tags', 't')
            ->join('p.tags', 'tmp')
            ->addSelect('t')
            ->andWhere('tmp.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getResult();
    }
}
